version: "3"
services:

  node-api:
    build: "."
    ports:
      - "5000:5000"
    links:
      - mongodb
      - redis
    working_dir: '/learnspace'
    volumes:
      - ".:/learnspace"

  mongodb:
    image: mongo
  
  redis:
    image: redis