version: "3"
services:
       
  node-api:
          build: "."
          ports:
                  - "5000:5000"
          links:
                  - mongodb
                  - redis
                  - mongodb-test
                  - redis-test
          volumes:
                  - "./src:/learnspace-api/src"
                  - "./__test__:/learnspace-api/__test__"
                  - "./package.json:/learnspace-api/package.json"
                  - "./yarn.lock:/learnspace-api/yarn.lock"

  mongodb:
           image: mongo

  redis:
          image: redis

  mongodb-test:
          image: mongo
  
  redis-test:
          image: redis
