version: "3"
services:

  node-api:
    build: "."
    ports:
      - "5000:5000"
    links:
      - mongodb
      - redis
    volumes:
      - "./src:/learnspace-api/src"
      - "./__test__:/learnspace-api/__test__"

  mongodb:
    image: mongo
  
  redis:
    image: redis
