version: "3"
services:

  node-api:
    restart: always
    build: "."
    ports:
      - "5000:5000"
    links:
      - mongodb
      - redis
    working_dir: '/learnspace'
    volumes:
      - "~/Desktop/projects/nodejs/learnspace-api:/learnspace"

  mongodb:
    image: mongo
    restart: always
  
  redis:
    image: redis
    restart: always

  reverse-proxy:
    image: nginx:stable-alpine
    restart: always
